[profile.default]
evm_version = "prague"
solc = "0.8.28" # Updated to ensure consistency
optimizer = true
optimizer_runs = 200
via_ir = true # Enabled by default for compatibility
bytecode_hash = "none"
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
gas_reports = ["*"]
gas_limit = "18446744073709551615"
dynamic_test_linking = true
ignored_warnings_from = ["test/","script/"]

remappings = [
    # Remappings from aid-contracts
    '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-oapp-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/',
    '@layerzerolabs/lz-evm-v1-0.7/=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/node_modules/@layerzerolabs/lz-evm-v1-0.7/',
    'hardhat-deploy/=lib/LayerZero-v2/packages/layerzero-v2/evm/messagelib/node_modules/hardhat-deploy/',
    '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable-v4/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts-v4/contracts/',
    '@openzeppelin-v5/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable-v5/contracts/',
    '@openzeppelin-v5/contracts/=lib/openzeppelin-contracts-v5/contracts/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
    '@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol=lib/openzeppelin-contracts-upgradeable-v4/contracts/access/OwnableUpgradeable.sol',
    'forge-std/=lib/forge-std/src/',

    # Remappings from original symbiotic-super-sum
    "node_modules/@symbioticfi/relay-contracts:@openzeppelin/contracts/=node_modules/@symbioticfi/relay-contracts/node_modules/@openzeppelin/contracts/",
    "node_modules/@symbioticfi/relay-contracts:@openzeppelin/contracts-upgradeable/=node_modules/@symbioticfi/relay-contracts/node_modules/@openzeppelin/contracts-upgradeable/",
    "node_modules/@symbioticfi/relay-contracts:@symbioticfi/rewards/=node_modules/@symbioticfi/rewards/",
    "node_modules/@symbioticfi/relay-contracts:@symbioticfi/core/=node_modules/@symbioticfi/relay-contracts/node_modules/@symbioticfi/core/",
    "@symbioticfi/relay-contracts/=node_modules/@symbioticfi/relay-contracts/src/",
    "@symbioticfi/core-contracts/=node_modules/@symbioticfi/core/"
]

[rpc_endpoints]
mainnet = "${ETH_RPC_URL}"
hoodi = "${ETH_RPC_URL_HOODI}"
holesky = "${ETH_RPC_URL_HOLESKY}"
sepolia = "${ETH_RPC_URL_SEPOLIA}"

[fmt]
bracket_spacing = false
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4

[fuzz]
runs = 4096
max_test_rejects = 262144

[lint]
lint_on_build = false
exclude_lints = ["asm-keccak256","mixed-case-function","mixed-case-variable","pascal-case-struct","screaming-snake-case-const"]
ignore = ["test/**/*.sol","script/**/*.sol","src/interfaces/**/*.sol"]

[[profile.default.compilation_restrictions]]
paths = "{script/**/*}"
via_ir = true
optimizer_runs = 1

[[profile.default.additional_compiler_profiles]]
name = "via-ir-1"
via_ir = true
optimizer_runs = 1

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options